platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.3.0

inputs:
  - name: flight-school
  
run:
  path: bash 
  args: 
    - ./flight-school/flight-school/ci/test.sh 

# run:
#   path: ls 
#   args: 
#     - -la
#     - flight-school/ci
